#!/usr/bin/perl
use strict;
use warnings;
my($firstnames, $surnames) = ("data/first-names", "data/surnames");
my(@firstnames, @surnames);

if(-T $firstnames && -T $surnames) {
	open(FIRSTNAMES, $firstnames);
	open(SURNAMES, $surnames)
} else { 
	die "Can't open namefiles: $!"
}
chomp(@firstnames=<FIRSTNAMES>);
chomp(@surnames=<SURNAMES>);

#picks a random element from an array
sub pick {
	return $_[int rand@_]
}

sub gen_name {
	return(&pick(@firstnames), &pick(@surnames))
}
for(1..10){
	my@test=&gen_name;
	print"@test\n"
}
